project:
  type: website

website:
  title: "Náhradníci"
  site-url: https://nahradnici.jfronc.cz/
  navbar:
    left:
      - psp/PSP.qmd
      - psp/psp_stats.qmd
      - about.qmd
    right: 
      - href: https://jfronc.cz/
        text: Jaromír Fronc
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


